### ISSUE TITLE
no cv.performance object in TissuesC.txt

### ISSUE THREAD

**Issue by humanpaingeneticslab** [TiffanyAmariuta/TCSC#1]
In all of tissues listed in TissuesC.txt there seem to be a lack of objects of type 'cv.performance' in the files 'ENSGxxxx.1.wgt.RDat'. This can be assessed by:

R --vanilla
load( "META_Brain_Limbic/Brain_Limbic.ENSG00000283438.1.wgt.RDat" )
ls()
[1] "snps"       "wgt.matrix"

**Comment by TiffanyAmariuta** [comment]
Hi Marc, 

Yes, that's right. That's because the tissues in TissuesC.txt were sample size weighted meta-analyzed, once the constituent tissue weights were each fit with cross-validation. Therefore, there are no straight-forward cv.performance statistics for these tissues across the 4 Fusion models: top1, enet, lasso, blup. To estimate accuracy, which is important for bias correction, we took the average accuracy across the constituent tissues.
